build:
  image: default-bionic
  environment:
    php:
      version: "8.1.4"
  nodes:
    coverage:
      tests:
        override:
          - command: composer phpunit
            coverage:
              file: coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run