language: php
env:
  global:
    - XDEBUG_MODE=coverage
php:
  - 8.1.4

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml